image_input_topic: "/camera/rgb/image_raw"
face_detected_image_topic: "/face_detector/raw_image"
haar_file_face: "/home/ghostman/ros_dev/catkin_ws/src/chefbot_facedetection/data/face.xml"
face_tracking: 1
display_original_image: 1
display_tracking_image: 1
